import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useSelector, useDispatch } from "react-redux";
import { asyncReceiveCountry } from "../../states/country/action";
import LineChart from "../../components/Chart/LineChart";

export default function Stats() {
  const router = useRouter();
  const { slug } = router.query;

  const { country = [] } = useSelector((states) => states);

  const dispatch = useDispatch();

  useEffect(() => {
    if (slug) {
      dispatch(asyncReceiveCountry(slug));
    }
  }, [slug, dispatch]);

  return (
    slug && (
      <>
        <Head>
          <title>
            {slug.charAt(0).toUpperCase() + slug.slice(1)} | Covid Tracker
          </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {country.length !== 0 && (
          <div className="flex flex-col h-auto max-w-xl p-5 m-5 mx-auto border rounded shadow-md lg:max-w-7xl">
            <Link href="/">
              {/* prettier-ignore */}
              <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 16l-4-4m0 0l4-4m-4 4h18" /></svg>
            </Link>
            <div className="flex items-center justify-between mt-4">
              <div className="flex items-center gap-x-4">
                <div className="relative w-16 h-12 border border-black">
                  <Image
                    src={`/flags/${country[0].CountryCode.toLowerCase()}.svg`}
                    alt={country?.Country}
                    layout="fill"
                    objectFit="cover"
                    quality={80}
                  />
                </div>

                <div>
                  <h2 className="text-lg font-semibold">
                    {country[0].Country}
                  </h2>
                  <p>{country[0].CountryCode}</p>
                </div>
              </div>
              <div>
                <p className="text-gray-500">Lat: {country[0].Lat}</p>
                <p className="text-gray-500">Lon: {country[0].Lon}</p>
              </div>
            </div>
            <LineChart dailyData={country} />
          </div>
        )}
      </>
    )
  );
}
