import Head from "next/head";
import { useEffect } from "react";
import { useSelector, useDispatch } from "react-redux";
import { asyncReceiveSummaries } from "../states/summaries/action";
import { changeData } from "../states/selected/action";
import LeftContent from "../containers/LeftContent";
import RightContent from "../containers/RightContent";

export default function Home() {
  const { summaries = [] } = useSelector((states) => states);

  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(asyncReceiveSummaries());
  }, [dispatch]);

  const handleCountryChange = (data) => {
    dispatch(changeData(data));
  };

  return (
    <>
      <Head>
        <title>Covid Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {summaries.length !== 0 && (
        <div className="flex flex-col h-auto px-6 py-10 lg:h-screen bg-gray-50 lg:flex-row lg:px-12">
          <LeftContent
            data={summaries}
            handleCountryChange={handleCountryChange}
          />
          <RightContent data={summaries.countries} />
        </div>
      )}
    </>
  );
}
